//index/jsp
home.Welcome=Welcome to bookstore,
home.WelcomeGuest=Welcome to bookstore, Guest
home.Name=Bookstore - Main
home.Catalog=Catalog
//login.jsp
login.Login=Login
login.Email=Email: 
login.Password=Password: 
//error.jsp
error.ErrorPage=Error Page
error.Error=Error
error.MessageError=Something went wrong!
//editBook.jsp
editBook.Title=Add Book
editBook.NewBook=Add new book
editBook.Name=Name
editBook.Author=Author
editBook.Price=Price
//books.jsp
books.Title=Books
books.Books=Books
books.BooksMessage=No books available!
books.First=First
books.Prev=Prev
books.Next=Next
books.Last=Last
books.Id=Id
books.Name=Name
books.Author=Author
books.Price=Price
//book.jsp
book.Title=Book
book.Book=Book
book.Id=Id
book.Name=Name
book.Author=Author
book.Price=Price
//addBook.jsp
addBook.Title=Create book
addBook.AddNewBook=Add new book
addBook.Name=Name
addBook.Author=Author
addBook.Price=Price
addBook.Create=Create
navbar.Store=Bookstore
navbar.Books=Books
navbar.Cart=Cart
navbar.Users=Users
navbar.AddBook=Add book
navbar.User=User
navbar.Login=Login
navbar.Logout=Logout
